### ISSUE TITLE
[IMPL-ISSUE] Uncertainty of `nonce` increase in `protocol-solidity`

### ISSUE THREAD

**Issue by duguorong009** [webb-tools/protocol-cosmwasm#54]
@drewstone @shekohex @nepoche 
In the current `(v)anchor` impl of `protocol-cosmwasm`, it just followed the code of `protocol-solidity`.
[anchor implementation in cosmwasm](https://github.com/webb-tools/protocol-cosmwasm/blob/main/contracts/anchor/src/contract.rs#L754)
[vanchor implementation in cosmwasm](https://github.com/webb-tools/protocol-cosmwasm/blob/main/contracts/vanchor/src/contract.rs#L990)

[AnchorBase in solidity](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/anchors/AnchorBase.sol#L173)

The issue is that the `solidity` version uses `1048` as kind of increment of `proposal_nonce`.
Can you provide the explanation for this number?

**Comment by shekohex** [comment]
Back then, the nonce used to be incremented by 1, as It should be right? the usage of nonces is of course essential. This update happened for the following reason: Imagine a deposit happened on an Anchor A that is linked to Anchor B on another chain, the relayer (or technically speaking anyone with a valid proposal data and signature) would update the other linked Anchor(s) with the new state. Now Imagine N deposits happened, the relayers/oracles are forced now to go through each one of them sequentially in the same order they happened and do the update to the other linked anchors, This is enforced by design since each proposal of `AnchorUpdateProposal` (also any sort of proposal) includes a `Nonce` and the nonce needs to be incremented by one. But technically, to update the state of the other linked anchors you only need the latest state at that time, the merkle root so we can batch all these updates into just one Proposal, thus we allowed the nonce to be incremented by this large amount.

**Comment by duguorong009** [comment]
Thanks for the quick & detailed reply!
Will fix the `protocol-cosmwasm`, regarding the explanation.
