### ISSUE TITLE
[PROTOCOL] How to get/set the `resource_id` in `protocol-cosmwasm`

### ISSUE THREAD

**Issue by duguorong009** [webb-tools/protocol-cosmwasm#55]
@drewstone @shekohex 
While implementing the integration tests for `SignatureBridge` contract of `protocol-cosmwasm`, 
I found that the current [Webb-proposal ResourceId](https://docs.rs/webb-proposals/latest/webb_proposals/index.html#the-resourceid) cannot be directly used in tests.  
According to the `Webb-proposal ResourceId`, the `resource_id` is combination of 
`target_contract_address(max 26 bytes)`, `chain_type(2 bytes)`, and `chain_id(4 bytes)`.

At the moment, the `(local) juno network` is used for tests. They use the contract address 
of length `63 bytes`("juno1" + 58 bytes address).
This bytes length difference causes the conflict & blocks the tests.
How can I overcome this issue & test the whole work flow of `SignatureBridge` in `protocol-cosmwasm`?

In addition, I done the research on `address`, `account`, `pubkey` of Cosmos-SDK blockchains.
Found that they use the `20 bytes pubkey` for representing the `account`.
But, for human-readable address, they use the `bech32` format.
Hence, normally the `address` is the combination of `chain-prefix` and `38 bytes string`, 
like `cosmos1....`, `juno1....`.
Surely, there is the special case like contract address(63 bytes total) in `juno`.

**Comment by shekohex** [comment]
We can introduce a new variant in the Webb Proposals target system, but right now we are limited to just 26 bytes for the target system. Here are some ideas we can do to solve this:

First I see here you already have a mapping [r_id => Addr](https://github.com/webb-tools/protocol-cosmwasm/blob/cfc3b0f22643e01843ab3d90564ad0050bec4d4a/contracts/signature-bridge/src/state.rs#L19) this should not be an issue? I don't think in Solidity we have this mapping since we can extract the contract address (the anchor, vanchor, ...) and from there we can read the handler address (afaik, needs to confirm that).

What we can do to solve this is we could treat them as Ethereum contract addresses like so `keccak256(address)` and then take the last 20 bytes (we could take the last 26 bytes here too if that would work better). and in the SignautreBridge Contract, we would store these hashes and map them to the actual address.

**Comment by drewstone** [comment]
I do not yet think this is correct @duguorong009. You may be talking about the # of characters in the address and not the bytes (you're overcounting). Looking at the docs here, it seems that hex-encoded addresses in Juno are still 20 bytes. Can you point to where your research led you to your conclusions? 

https://docs.junonetwork.io/cli/modules/debug#junod-debug-addr

**Comment by drewstone** [comment]
@shekohex has the right idea as well if we are going to keep our proposal formats the same. We would maintain an extra map from the hash of contract addresses to the actual contract address in question where needed. We should explore this a bit and identify if there are issues that prompt another proposal format update.

**Comment by duguorong009** [comment]
I also think @shekohex indicated the right direction.
Using the convert function like `hashing & slicking` is needed for consistency of the existing proposal system.

I think we should introduce a new mapping in the `signature-bridge` for above purpose.
@shekohex mentioned that there already exists [r_id=>Addr](https://github.com/webb-tools/protocol-cosmwasm/blob/cfc3b0f22643e01843ab3d90564ad0050bec4d4a/contracts/signature-bridge/src/state.rs#L19) in the current implementation.
But, it is for mapping of `(v)anchor_contract_id => handler`.
Hence, I think we should add extra mapping to store the mapping of `r_id => real (v)anchor address`.
Will try to implement it & ask for review.

**Comment by duguorong009** [comment]
Thanks @shekohex 
It looks like we go for process - `keccak256 hashing & take last 20 bytes for r_id`.
Got it.

I think we should add this extra info for `protocol-cosmwasm` in the [webb-proposals](https://docs.rs/webb-proposals/latest/webb_proposals/index.html#the-resourceid).
right?

**Comment by shekohex** [comment]
> I think we should add this extra info for protocol-cosmwasm in the [webb-proposals](https://docs.rs/webb-proposals/latest/webb_proposals/index.html#the-resourceid).
right?

Yes, adding that to the docs in the `TargetSystem` would be helpful. once implemented and it works as expected, I would recommend opening a PR to update the docs too.
